services:

  db:
    image: postgres:16

    container_name: mercado_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mercado_api

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: .

    container_name: mercado_api

    restart: always

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/mercado_api
      SECRET_KEY: 123456
      ALGORITHM: HS256
      TEMPO_EXPIRACAO: 30

    depends_on:
      - db


volumes:
  postgres_data: